name: Runner

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run_app:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.2'
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
    - name: Check RSS updates and send them over email.
      env:
        MINIFLUX_URL: ${{ secrets.MINIFLUX_URL}}
        MINIFLUX_TOKEN: ${{ secrets.MINIFLUX_TOKEN }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SEND_TO: ${{ secrets.TO_EMAIL }}
        CGO_ENABLED: 0
        CATEGORY: daily
      run: |
        go run main.go
